[package]
name = "chalamet_pir"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
sha3 = "=0.10.8"
rand = "=0.8.5"
rand_chacha = "=0.3.1"
serde = { version = "=1.0.217", features = ["derive"] }
bincode = "=1.3.3"
rayon = "=1.10.0"

[dev-dependencies]
divan = "=0.1.17"

[[bench]]
name = "offline_phase"
harness = false

[[bench]]
name = "online_phase"
harness = false
required-features = ["mutate_internal_client_state"]

[features]
mutate_internal_client_state = []

[profile.optimized]
inherits = "release"
codegen-units = 1
lto = "thin"

[profile.test-release]
inherits = "release"
debug = true
debug-assertions = true
overflow-checks = true
