[package]
name = "chalamet_pir"
version = "0.2.0"
edition = "2021"
resolver = "2"
rust-version = "1.84.0"
authors = ["Anjan Roy <hello@itzmeanjan.in>"]
description = "Simple, Stateful, Single-Server Private Information Retrieval for Key-Value Databases"
documentation = "https://github.com/itzmeanjan/ChalametPIR"
readme = "README.md"
repository = "https://github.com/itzmeanjan/ChalametPIR.git"
license = "MPL-2.0"
keywords = ["priv-info-retrieval", "lwe-pir", "frodo-pir", "chalamet-pir"]
categories = ["cryptography", "data-structures"]

[dependencies]
sha3 = "=0.10.8"
rand = "=0.9.0"
rand_chacha = "=0.9.0"
serde = { version = "=1.0.217", features = ["derive"] }
bincode = "=1.3.3"
rayon = "=1.10.0"

[dev-dependencies]
divan = "=0.1.17"
unicode-xid = "=0.2.6"

[[bench]]
name = "offline_phase"
harness = false

[[bench]]
name = "online_phase"
harness = false
required-features = ["mutate_internal_client_state"]

[features]
mutate_internal_client_state = []

[profile.optimized]
inherits = "release"
codegen-units = 1
lto = "thin"

[profile.test-release]
inherits = "release"
debug = true
debug-assertions = true
overflow-checks = true
