# Taken from https://github.com/itzmeanjan/ascon/blob/644e5c0ee64da42e3c187adb84ba4c43925caf30/.github/workflows/test_ci.yml
name: Test ChalametPIR - Private Information Retrieval for Key-Value Maps

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        # See https://docs.github.com/en/actions/writing-workflows/choosing-where-your-workflow-runs/choosing-the-runner-for-a-job#standard-github-hosted-runners-for-public-repositories
        # for available targets.
        os: [
            ubuntu-latest, # x86-64
            ubuntu-24.04-arm, # arm64

            macos-13, # x86_64
            macos-latest, # arm64

            windows-latest, # x86_64
            windows-11-arm # arm64
            ]

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Increase Rust Compiler stack size
        run: echo "RUST_MIN_STACK=67108864" >> $GITHUB_ENV

      - name: Build and Test on ${{ matrix.os }}
        run: cargo test --profile test-release

      - name: Run Example on ${{ matrix.os }}
        run: cargo run --example kw_pir --profile optimized
