# Taken from https://github.com/itzmeanjan/ascon/blob/644e5c0ee64da42e3c187adb84ba4c43925caf30/.github/workflows/test_ci.yml
name: Test ChalametPIR - Private Information Retrieval for Key-Value Maps

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        # See https://docs.github.com/en/actions/writing-workflows/choosing-where-your-workflow-runs/choosing-the-runner-for-a-job#standard-github-hosted-runners-for-public-repositories
        # for available targets.
        os: [
            ubuntu-latest, # x86-64
            ubuntu-24.04-arm, # aarch64
            macos-latest, # aarch64
            macos-13, # x86_64
            windows-latest # x86_64
            ]

    steps:
      - uses: actions/checkout@v4

      - name: Build and Test on ${{ matrix.os }}
        run: cargo test --profile test-release

      - name: Run Example on ${{ matrix.os }}
        run: cargo run --example kw_pir --profile optimized
